language: node_js
node_js:
  - "stable"
cache: false
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: master
  fqdn: www.maltsev.space
before_script:
  - "rm -rf node_modules/"
  - "npm i -g gatsby"
  - "npm i"
script:
  - "npm run test"
after_success:
  - "npm run deploy"